name: test-security-and-analysis-dependabot_security_updates
path: test-security-and-analysis-dependabot_security_updates.rego

level: warning

description: "A rule to verify that dependabot_security_updates in security_and_analysis is properly set"

evidence:
  signed: false
  format-type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=repository"

