name: test-binary-fields-dependabot_security_updates_enabled_for_new_repositories
path: test-binary-fields-dependabot_security_updates_enabled_for_new_repositories.rego

level: warning

description: "A rule to verify that the binary field: dependabot_security_updates_enabled_for_new_repositories is properly set"

evidence:
  signed: false
  format-type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=organization"

with:
  desired_value: false # Enter true or false