name: use-of-a-specific-secret
path: use-of-a-specific-secret.rego

level: warning

description: "A rule to verify that certain secrets are not accessible"

evidence:
  signed: false
  format-type: generic
  target_type: data
  predicate_type: http://scribesecurity.com/evidence/discovery/v0.1
  labels:
    - "asset_type=pod"

# Implementation not complete
with:
  secret-to-check:
  
